version: '2'

# Linters configuration
linters:
  # Enable specific linters
  enable:
    # Core linters (enabled by default, but listing for clarity)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional security linters
    - gosec
    - goconst
    - gocyclo
    - misspell
    - unconvert
    - unparam
    - gocritic
    - whitespace
    # Performance linters
    - prealloc
    # Style linters
    - godot
    - revive
    # Error handling
    - errname
    - errorlint
    - wrapcheck
    # Import organization
    - goimports
    - gci
    # Code complexity
    - nestif
    - funlen
    # Additional quality checks
    - dupl
    - exportloopref
    - nolintlint
  disable:
    # Disable overly strict linters for game development context
    - exhaustruct # Too strict for configuration structs
    - varnamelen # Short variable names are fine in limited scopes
    - ireturn # Interface returns are sometimes necessary
    - wsl # Whitespace linter can be too opinionated

# Run configuration
run:
  timeout: 5m
  go: '1.24'
  tests: true
  build-tags:
    - mage
  skip-dirs:
    - build
    - bin
    - tmp
    - vendor
    - .mage
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"
    - ".*_templ\\.go$"

# Formatters configuration (v2 feature)
formatters:
  gofmt:
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/dunamismax/ideal-magic

# Linter-specific settings
linters-settings:
  gosec:
    # Exclude some security checks that are false positives for games
    excludes:
      - G404 # Use of weak random number generator is OK for non-crypto uses
      - G501 # Blacklisted import crypto/md5: weak cryptographic primitive (OK for non-security hashing)

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true
    ignore-calls: true

  gocyclo:
    min-complexity: 15

  nestif:
    min-complexity: 5

  funlen:
    lines: 80
    statements: 50

  misspell:
    locale: US
    ignore-words:
      - forge
      - mana
      - tcg
      - gameplay
      - cardstock
      - rulebook

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - commentFormatting
      - whyNoLint
      - hugeParam
      - rangeValCopy

  goimports:
    local-prefixes: github.com/dunamismax/ideal-magic

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/dunamismax/ideal-magic)
    skip-generated: true

  revive:
    rules:
      - name: exported
        disabled: true # We use other linters for this
      - name: package-comments
        disabled: true # Not always needed for small packages
      - name: line-length-limit
        arguments: [120]

  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - fmt.Errorf(
    ignorePackageGlobs:
      - github.com/pkg/errors
      - github.com/magefile/mage/*

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  dupl:
    threshold: 100

# Issues configuration
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false # Show all issues, not just new ones
  fix: false # Don't auto-fix issues

  # Exclude specific issues
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        - funlen
        - nestif

    # Exclude some issues in main.go (entry point)
    - path: main\.go
      linters:
        - gochecknoinits # Init functions are OK in main
        - funlen # Main function can be longer

    # Exclude some issues in magefile.go (build script)
    - path: magefile\.go
      linters:
        - gochecknoinits # Init functions are OK in magefiles
        - funlen # Build functions can be longer
        - gocyclo # Build logic can be complex
        - nestif # Build conditionals can be nested

    # Exclude magic number checks for common HTTP/port values
    - text: 'Magic number: (200|400|401|403|404|500|429|8080|3000|443|80)'
      linters:
        - gomnd
        - goconst

    # Exclude magic number checks for common game values
    - text: 'Magic number: (60|120|300|600|7|20|40)'
      linters:
        - gomnd
        - goconst

    # Allow TODO comments in early development
    - text: 'Line contains TODO'
      linters:
        - godox

  # Global exclusions
  exclude:
    # Allow blank imports for Go 1.24 embedding
    - 'blank-imports'

# Output configuration
output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

# Severity configuration
severity:
  default: error
  case-sensitive: false
  rules:
    - linters:
        - misspell
        - goconst
        - godot
        - whitespace
      severity: warning
    - linters:
        - gosec
        - errcheck
        - staticcheck
        - govet
        - ineffassign
        - unused
      severity: error
