baseURL = 'https://forge-realm.com'
languageCode = 'en-us'
title = 'Forge Realm - Open Source Trading Card Game'
contentDir = 'content'
enableEmoji = true

[module]
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
    disable = false
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true

[params]
  github_repo = 'https://github.com/dunamismax/forge-realm'
  github_branch = "main"

  [params.docs]
    title = "Forge Realm Documentation"
    darkMode = true
    prism = true

  [params.social]
    github = "https://github.com/dunamismax/forge-realm"
    discord = "https://discord.gg/KQTY8DfY"

[menu]
  [[menu.primary]]
    name = "Documentation"
    url = "/docs/"
    weight = 10
  [[menu.primary]]
    name = "Cards"
    url = "/cards/"
    weight = 15

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]