baseURL = 'https://forge-realm.com'
languageCode = 'en-us'
title = 'Forge Realm TCG'
contentDir = 'content'
enableEmoji = true
enableRobotsTXT = true
enableGitInfo = true
hasCJKLanguage = false

[module]
  [module.hugoVersion]
    extended = true
    min = "0.146.0"
  replacements = "github.com/imfing/hextra -> ./themes/hextra-theme"
  [[module.imports]]
    path = "github.com/imfing/hextra"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\[', '\]']]
          inline = [['\(', '\)']]
  [markup.highlight]
    noClasses = false

enableInlineShortcodes = true

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    identifier = "documentation"
    name = "Documentation"
    pageRef = "/docs"
    weight = 1
  [[menu.main]]
    name = "Cards"
    pageRef = "/docs/cards"
    weight = 2
  [[menu.main]]
    name = "Gameplay"
    pageRef = "/docs/gameplay"
    weight = 3
  [[menu.main]]
    name = "Printing"
    pageRef = "/docs/printing"
    weight = 4
  [[menu.main]]
    name = "Search"
    weight = 5
    [menu.main.params]
      type = "search"
  [[menu.main]]
    name = "Discord"
    weight = 6
    url = "https://discord.gg/KQTY8DfY"
    [menu.main.params]
      icon = "discord"
  [[menu.main]]
    name = "GitHub"
    weight = 7
    url = "https://github.com/dunamismax/forge-realm"
    [menu.main.params]
      icon = "github"


[params]
  description = "Pure Magic: The Gathering as it was meant to be - focusing on Vintage and Modern's most beloved mechanics with modern enhancements."

  [params.navbar]
    displayTitle = true
    displayLogo = true
    width = "wide"
    [params.navbar.logo]
      path = "images/forge-realm-PNG-circular-emblem.webp"
      dark = "images/forge-realm-PNG-circular-emblem.webp"
      width = 40
      height = 40

  [params.theme]
    default = "dark"
    displayToggle = true

  [params.footer]
    enable = true
    displayCopyright = true
    displayPoweredBy = false
    width = "normal"

  displayUpdatedDate = true
  dateFormat = "January 2, 2006"

  [params.search]
    enable = true
    type = "flexsearch"
    [params.search.flexsearch]
      index = "content"
      tokenize = "forward"

  [params.editURL]
    enable = true
    base = "https://github.com/dunamismax/forge-realm/edit/main/content"

  [params.toc]
    displayTags = true

  [params.highlight]
    [params.highlight.copy]
      enable = true
      display = "hover"

  [params.page]
    width = "normal"

  [params.comments]
    enable = false
  
  copyright = "© 2025 Forge Realm."
  github_repo = "https://github.com/dunamismax/forge-realm"
  github_branch = "main"
  github_project_repo = "https://github.com/dunamismax/forge-realm"
