name: Documentation Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check markdown formatting
      uses: DavidAnson/markdownlint-cli2-action@v15
      with:
        globs: '**/*.md'
        
    - name: Check links
      uses: lycheeverse/lychee-action@v1
      with:
        args: '**/*.md'